// This file is generated by npm run build:icons
 
export type IconName =
	| "contact"
	| "facebook"
	| "home"
	| "instagram"
	| "log-in"
	| "log-out"
	| "menu"
	| "moon"
	| "search"
	| "shopping-cart"
	| "star"
	| "sun"
	| "twitter";
